# ================================================================
# Home Assistant Crop Steering Package
# Advanced Irrigation Management System for Home Assistant
# ================================================================
#
# This package provides a comprehensive crop steering irrigation system
# with advanced analytics, sensor fusion, ML predictions, and multi-crop support.
#
# REQUIREMENTS:
# - Home Assistant 2024.3 or later (for modern template format)
# - AppDaemon 4.2+ for automation logic (crop_steering_app.py)
# - VWC (Volumetric Water Content) sensors
# - EC (Electrical Conductivity) sensors
# - Irrigation control valves/pumps
#
# FEATURES:
# - 4-phase crop steering cycle (P0-P3)
# - Multi-crop profile support (Cannabis, Tomato, Lettuce, Basil, Custom)
# - Advanced sensor fusion with outlier detection
# - ML-based dryback prediction and pattern recognition
# - Comprehensive analytics and performance monitoring
# - MQTT remote monitoring and control
# - Anomaly detection and alerting
# - Growth stage prediction and recommendations
#
# PACKAGE STRUCTURE:
# - Core input helpers: cs_input_*.yaml files
# - Template sensors: cs_template_entities.yaml
# - Analytics engine: cs_analytics_*.yaml files
# - Sensor fusion: cs_sensor_fusion_*.yaml files
# - ML analytics: cs_ml_*.yaml files
# - MQTT monitoring: cs_mqtt_*.yaml files
# - Crop profiles: cs_crop_profiles.yaml
# - Dashboard cards: cards/ directory
#
# INSTALLATION:
# 1. Place this entire CropSteering directory in your packages/ folder
# 2. Add "packages: !include_dir_named packages" to configuration.yaml
# 3. Install AppDaemon and configure crop_steering_app.py
# 4. Configure your sensors in the input helpers
# 5. Restart Home Assistant
#
# CONFIGURATION:
# - Adjust sensor entity_ids in cs_input_texts.yaml
# - Set crop type in cs_input_selects.yaml
# - Configure irrigation parameters in cs_input_numbers.yaml
# - Enable features in cs_input_booleans.yaml
#
# ================================================================

# Include all input helper files for each domain
input_select: !include_dir_merge_named .
input_number: !include_dir_merge_named .
input_boolean: !include_dir_merge_named .
input_text: !include_dir_merge_named .
input_datetime: !include_dir_merge_named .

# Include all template sensors and binary_sensors
template: !include_dir_merge_list .

# Include automation files (MQTT monitoring includes some automations)
automation: !include_dir_merge_list .

# ================================================================
# AUTOMATION NOTES:
# ================================================================
# Primary automation logic is handled by AppDaemon (crop_steering_app.py)
# Additional automations included from:
# - cs_mqtt_monitoring.yaml (MQTT publishing and command handling)
# 
# If not using AppDaemon, you would need to create additional automation
# files to replace the AppDaemon logic for:
# - Phase transitions (P0->P1->P2->P3)
# - Irrigation triggering based on VWC thresholds
# - Dryback monitoring and calculations
# - Shot counting and timing
# ================================================================
