name: Rollback (disabled)

on:
  workflow_call:

permissions:
  contents: none

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  noop:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rollback workflow is disabled"
